spring:
  datasource:
    url: jdbc:mysql://192.168.1.108:3306/sell?characterEncoding=utf-8&userSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  redis:
    host: 192.168.1.108
    port: 6379
    password:
  freemarker:
    settings:
     number_format: "0.##"
#
server:
  servlet:
    context-path: /sell

wechat:
#  微信公众平台测试号appid 和 密钥  授权
  mpAppId: wxd898fcb01713c658
  #测试号
#  mpAppId: wxdc78d2e9019e2302
#  mpAppSecret: 2f92d95e851b84e9d7dd9d8fe63d19e0

#  微信开放平台的appid 和 密钥 扫码登录使用
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e

#  支付平台/商品号
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
#  异步通知
  notifyUrl: http://canloveme.natapp.cc/sell/pay/notify
  KeyPath: E:\IdeaProgects\bishe\src\main\resources\h5.p12
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projecturl:
  wechatMpAuthorize: http://canloveme.mynatapp.cc
  wechatOpenAuthorize: http://canloveme.mynatapp.cc
  sell: http://canloveme.mynatapp.cc

# 又拍云服务 见 https://console.upyun.com/services/file/
#upyun:
#  bucketName: XXX
#  userName: xxx
#  password: xxxx
#  imageHost: http://xxx.com/
